### ISSUE TITLE
Crash On Intro Osu! After enable disable triangle 

### ISSUE THREAD

**Issue by DannyKurniawan642** [ojh050118/osu-test#14]
![20200101_061147_rmscr](https://user-images.githubusercontent.com/49144332/71636052-b8122900-2c5d-11ea-9539-82bf816d6adb.jpg)

**Comment by ojh050118** [comment]
디바이스 정보와 로그 파일을 업로드 하세요.
Upload device information and log files.

**Comment by DannyKurniawan642** [comment]
Motorola E4 Plus
RAM 3GB
ROM 32GB

Logs:
[runtime.log](https://github.com/ojh050118/osu-test/files/4013777/runtime.log)
[performance.log](https://github.com/ojh050118/osu-test/files/4013778/performance.log)
[database.log](https://github.com/ojh050118/osu-test/files/4013779/database.log)
[network.log](https://github.com/ojh050118/osu-test/files/4013780/network.log)

**Comment by ojh050118** [comment]
There seems to be no problem with the app. Please uninstall the app and update to the new version. [(2019.1227.0)](https://github.com/ojh050118/osu-test/releases/tag/2019.1227.0)

**Comment by DannyKurniawan642** [comment]
Still

**Comment by ojh050118** [comment]
Delete app data and reinstall. Uninstalling the app usually resets the options.
